### ISSUE TITLE
Just a simple question?

### ISSUE THREAD

**Issue by iUltimateLP** [LMSDev/W_D-Hook#1]
Hey, I know I know this is past 1 year, but I have a simple question.. The hook doesnt seem to load, because there's no log file, and I bet they didn't update the game that hard.. Could you tell me why?
Thanks :)

**Comment by LMSDev** [comment]
The hook doesn't work on the latest game version, but as far as I remember a log file should always be created. Please make sure all dependencies for the hook dll are installed (by using Dependency Walker for instance). You can also debug the _LoadLibrary_ call in the DInput8 proxy to return an error if the injection didn't work.

**Comment by iUltimateLP** [comment]
I went over it with Dependency Walker, but I'm not sure what to do with this information from there.. Many modules are red, and If I take out the proxy dinput8,  it loads the one from System32 and it shows way more functions with adresses than the proxy one (that only shows "CreateDirectInput8").. No log file being generated at all, which means that the proxy is the problem and not the main Script hook DLL...

Edit: 
![image](https://cloud.githubusercontent.com/assets/8491339/13217486/081e4cd2-d963-11e5-8622-c86b2cbb9c38.png)
Thats how dependency walker sees my hook.. I added some code in the hook to show MessageBoxes on load, but they don't show up either:
![image](https://cloud.githubusercontent.com/assets/8491339/13217498/269e1520-d963-11e5-8256-e07db857a4ff.png)

Edit2: I also tried this code in the DirectInput8Create method to generate a simple text file, but that doesn't work either:

```
    InitializeCriticalSection(&lock);
    logfile = fopen("log.txt", "at");

    EnterCriticalSection(&lock);
    fprintf(logfile, "DirectInput8Create");

    EnterCriticalSection(&lock);
    fflush(logfile);
    fclose(logfile);
    logfile = NULL;
    LeaveCriticalSection(&lock);
    DeleteCriticalSection(&lock);
```

So it seems like the function is not called.. And if DllMain is called, I can't tell because I have no idea how to debug that because MessageBoxes wont work..

Edit3: Analyzing this with ProcMon to see if the DLL is even loaded, and it seems like:
![image](https://cloud.githubusercontent.com/assets/8491339/13221907/e6f43632-d97d-11e5-9991-f3940c4f7681.png)

Edit4: Okay, this is the last thing I tried and even that didn't work.. Sorry for spamming here :stuck_out_tongue: I tried this in DllMain:

```

BOOL APIENTRY DllMain(HMODULE hModule, DWORD  ul_reason_for_call, LPVOID lpReserved)
{
    FILE *f;
    fopen_s(&f, "F:\\[!] SteamLibrary\\SteamApps\\common\\Watch_Dogs\\bin\\log.txt", "a+");

    switch(ul_reason_for_call)
    {
        case DLL_PROCESS_ATTACH:
            {
                CreateThread(0, 0, lpDllLoadingThread, 0, 0, 0);
                fprintf(f, "DLL attached\n");
                break;
            }
    }

    fclose(f);

    return TRUE;
}
```

As you can see, with absolute file paths and all that stuff, and the log file remains empty. I'm not sure why this happens because ProcMon showed that the DLL is loaded, so why can't I see anything from the DLL. Maybe you could send me the DLL you use, but I don't think I made something wrong at compiling..

**Comment by iUltimateLP** [comment]
By the way: Bist du deutsch?

**Comment by LMSDev** [comment]
Hm, this is odd behavior indeed. Did you try a message box directly in DllMain? Also, is there any chance they introduced some anti-cheat at some point that might be blocking this? Try creating an empty text file and rename it to DInput8.dll and see if that crashes. 

And yes, I am german, but I'd like to continue this discussion in english if possible.

**Comment by iUltimateLP** [comment]
MessageBoxes don't work in DllMain since they are from user32.dll and nearly everything is blocked there for security reasons.. Also, I think its very unlikely that they made an Anti-Cheat module for a game that is nearly 2 years old, because it seems like it used to work in November '15, where one guy commented on your blog post.. I'll the text file test tomorrow!

**Comment by LMSDev** [comment]
They do work, it's not really recommended though. I use it a lot while manually unpacking. Yeah, it would be and it's really odd a simple dll proxy doesn't work. Let me know how it goes!

**Comment by iUltimateLP** [comment]
Well, ok, when I tried MessageBoxes directly in DllMain, they didn't work either.. I'll try the Text file test today, maybe if you find some time you can try the hook with the newest version aswell?

**Comment by iUltimateLP** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/8491339/13287264/5798b8f2-db06-11e5-8a7b-e5642ff077c4.PNG)
So the text file trick worked, it crashes.. I'll try the MessageBox inside the DllMain

Edit: Tried it, no message box shows up with code:

```
BOOL APIENTRY DllMain(HMODULE hModule, DWORD  ul_reason_for_call, LPVOID lpReserved)
{
    MessageBox(0, "Hello", "Hello", MB_OKCANCEL);

    switch(ul_reason_for_call)
    {
        case DLL_PROCESS_ATTACH:
            {
                CreateThread(0, 0, lpDllLoadingThread, 0, 0, 0);
                break;
            }
    }

    return TRUE;
}
```

**Comment by iUltimateLP** [comment]
Did you find anything out yet? I think I give this up, it seems like a simple proxy doesn't work like it should..

**Comment by LMSDev** [comment]
I never had problems with DllMain not getting called, so I'm not sure what exactly is happening here. If you are still interested, you could try to load the dll from another program to see if it loads at all.

**Comment by iUltimateLP** [comment]
I tried to load it from another game, Just Cause 3, in this case, and the MessageBox won't show either. Maybe I did something wrong with compiling? I gave him the .def file in the Linker settings, maybe something I'm missing?

**Comment by LMSDev** [comment]
Could be. You can check the symbols you are exporting (e.g. using Dependency Walker) to see if DllMain and the DInput8 functions are exported correctly. Note that they are required to be exported unmangled (C-style).

**Comment by iUltimateLP** [comment]
![image](https://cloud.githubusercontent.com/assets/8491339/13379237/8034a114-de20-11e5-98c9-9319fc935a66.png)
This looks kind of empty... Maybe this is wrong because DllMain isn't even visible there..

**Comment by iUltimateLP** [comment]
Okay, I wrote a simple application on my own to test whether the DllMain works. And the result: it does!
Console App code I tested it with:

```
#include "stdafx.h"
#include <iostream>
#include <windows.h>

using namespace std;

int main()
{
    cout << "Starting DLL loader." << endl;

    HMODULE hLib = LoadLibrary("_dinput8.dll");

    if (hLib)
    {
        cout << "DLL loaded. (" << hLib << ")" << endl;
    }
    else
    {
        cout << "DLL couldn't be loaded." << endl;
    }

    system("pause");

    return 0;
}
```

If I remove the file, it says DLL couldn't be loaded. If I place the compiled dll inside, it says DLL loaded and the adress of it and I see the message box of DllMain:
![image](https://cloud.githubusercontent.com/assets/8491339/13379808/dc641662-de30-11e5-8f98-a6f50ad5b9ef.png)

**Comment by LMSDev** [comment]
Hah, you got me while commenting. To address your earlier comment, the Dep Walker output looks fine. Also, good to hear the dll basically works. I just downloaded the source code and compiled it myself and tried it for The Witcher 3 and my dll got loaded just fine. Can you try this one for W_D? http://lms-dev.com/files/dinput8.rar It will show a message box when loaded.

**Comment by iUltimateLP** [comment]
Yep, when I use your DLL, the message box shows, tried it for Watch_Dogs, Just Cause 3 and also Witcher.. So what is different between your compiling and mine.. Wait, when I boot up the project for the first time in VS2015, I get a message that the project has older compiler settings and he needs to upgrade them, so I click yes, otherwise it can't compile. Maybe something with that?

**Comment by LMSDev** [comment]
Do you maybe compile your dll as x86 by accident? Remember that W_D is a x64 game.

**Comment by iUltimateLP** [comment]
Shit.. Real shit.. I thought it was x64 so I didn't check it.

**Comment by LMSDev** [comment]
So I take it, it works now? :)

**Comment by iUltimateLP** [comment]
The hook does work now. Now I go on with testing if the script hook works and stuff. If I have a problem, I'll write here again :) Thanks for all the help!

**Comment by LMSDev** [comment]
Great to hear! No problem, I'd appreciate it if you would fork and/or contribute to this repo if you get the hook working for the latest version, too. That way others can benefit as well.

**Comment by iUltimateLP** [comment]
Sure. I guess I have the next problem. They hook isn't loaded as a module. 

```
DWORD WINAPI lpDllLoadingThread(LPVOID lpParam)
{     
    // Load hook
    HMODULE hHook = LoadLibraryA("WatchDogsScriptHook.dll");

    if (hHook)
    {
        MessageBox(NULL, "Loaded script dll", "Hook", NULL);
    }
    else
    {
        MessageBox(NULL, "Couldn't load script dll", "Hook", NULL);
    }

    return 0;
}
```

I see the Couldn't load MessageBox, even though the dll is in the same directory than the dinput8.dll (and yes, it's x64 :joy:)

**Comment by LMSDev** [comment]
Make sure all dependencies are installed. For better understanding of the real error, call GetLastError after the call failed.

**Comment by iUltimateLP** [comment]
Yup, GetLastError() was 126, and dependency walker told me that FW1FontWrapper.dll is missing, so I copied it over and voila, it works. Now I can test the script hook for the first time xD

**Comment by iUltimateLP** [comment]
![image](https://cloud.githubusercontent.com/assets/8491339/13380156/46f02a10-de3c-11e5-9119-b526b392ac43.png)
LMAO take a look on that screenshot. It seems like the game fails loading some external dlls or something, because videos at beginning and in the main menu won't play (bink2w64.dll) and also many textures aren't loaded... And also uPlay doesn't work in-game, so that dll isn't loaded also.. Does the hook prevent the game from loading other dlls?

Edit: Nothing with dlls. Direct3D hook. When I comment out the Initialization of D3D, everything looks as intended. Strange

**Comment by iUltimateLP** [comment]
And also the game crashes when you're trying to load lua scripts. I bet this is because the Lua State adress has changed, but I don't know how to get the adress. In the blog, you said something about IDA, but that costs money..

**Comment by iUltimateLP** [comment]
I tried to use x64dbg, but to be honest, I understand nothing. I tried to search for Lua strings, but found nothing..

**Comment by LMSDev** [comment]
The D3D hook probably doesn't save a state before doing it's own logic, that is (now) required by the game. Make sure to backup all states and restoring them in the callback. As for the lua state, if you have no experience with reverse engineering, it's going to be a long journey, but could work as a cool project to get into it! x64dbg is not too bad and there are also "free" versions of IDA on the internet...

**Comment by iUltimateLP** [comment]
I tried both the free version of IDA and x64dbg, but both did not help me. I searched for stuff containing "lua" but found nothing.. Maybe If you find some time, you could explain the basics? I mean, you're german aswell and maybe you'd like to join a TeamSpeak server or something :joy:

**Comment by LMSDev** [comment]
I'm sorry but I don't have the time to look at W_D again or guide you through reversing. You have to learn it yourself a little bit and see how far you can get. For specific questions, feel free to ask me though.

**Comment by iUltimateLP** [comment]
I learned basic knowledge about x64dbg today with patching a password check to show that the password was correct everytime, even if not :joy:. I'm a bit unsure about how I would proceed in order to find the lua functions, since I cant see any human readable stuff in the disrupt_b64.dll assembly...

**Comment by iUltimateLP** [comment]
Okay I loaded once Disrupt_b64.dll and watch_dogs.exe inside IDA (64bit - found a free version somewhere) and now I can see stuff like .text:000000140004000 aswell, but everytime I search through, nothing like "lua" can be found..

**Comment by iUltimateLP** [comment]
Using x64dbg again because I can't really see anything with IDA because it doesn't want to attach to the running process of Watch_Dogs.exe, and I found the following:

```
00007FFBE4A9C680 | lea rdx,qword ptr ds:[7FFBE732F458] | 7FFBE732F458:"luaopen_%s"     
00007FFBE4A9E863 | lea r8,qword ptr ds:[7FFBE732FCA8]  | 7FFBE732FCA8:"_G"     
00007FFBE4A9E87E | lea rdx,qword ptr ds:[7FFBE732FCA8] | 7FFBE732FCA8:"_G"      
00007FFBE4A9E8A2 | lea r8,qword ptr ds:[7FFBE732FC90]  | 7FFBE732FC90:"_VERSION"      
00007FFBE4A9E88D | lea rdx,qword ptr ds:[7FFBE732FCA0] | 7FFBE732FCA0:"Lua 5.1"      
```

So what do the adresses mean like "7FFBE732FCA0". Am I right with the statement that if I try and get the value of "7FFBE732FC90" I should get the version of lua? In your hook, your adresses look really different from those..

**Comment by LMSDev** [comment]
I think Disrupt_b64 is packed and thus has to be dumped from the live process (tools like Scylla can help here). You are definitely heading in the right direction with the x64dbg research though.

Note that addresses don't really matter though (as you said mine looked a lot different). Addresses are based on the process base address which differs from session to session. Also the various patches to W_D probably also changed a lot of stuff. Check where those strings are used to determine where certain functions are. Those two screenshots should help you naming a few lua functions if you can locate the same strings (you seem to have the version one already):

![lua_ida_1](https://cloud.githubusercontent.com/assets/10090087/13904177/3ed536ec-ee98-11e5-89e5-ccf62b7125dd.jpg)
![image](https://cloud.githubusercontent.com/assets/10090087/13904198/a6cf4bb6-ee98-11e5-96fe-7437d8359b70.png)

Good luck and keep me in the loop :)

**Comment by iUltimateLP** [comment]
![image](https://cloud.githubusercontent.com/assets/8491339/13905891/90926b1a-eecc-11e5-8443-39db1ad3b2c8.png)
It seems like I was / am in the same region that you are. But in your image, instead of **call disrupt_b64.7FFD426F8AB0** you see **call luaL_register**.. So your pointers to functions are some kind of "encoded"? How can I reach that state?

**Comment by LMSDev** [comment]
I gave you a screenshot of how the area looks in my analyzed IDB so you can carry over the names. Originally I saw stuff like "call disrupt_b64.." too but since I figured out the real purpose of the function, I assigned a name to it. That's all. My screenshots are intended to give you a head start in analyzing the lua functions and finding the remaining ones.

**Comment by iUltimateLP** [comment]
Yeah I understood that, but how did you figure out which lua function belongs to which call instruction?

**Comment by LMSDev** [comment]
I looked at the function's instructions and how they are called in order to make sense of them. In addition, I checked the lua source code to see if that helps matching functions.

**Comment by iUltimateLP** [comment]
Ahh I think I unterstand it! Well then I need to learn a bit of those instructions first before I proceed! Thanks for help and I'll post my progress here :+1:

**Comment by wasdennnoch** [comment]
@iUltimateLP It's been 1.5 years since this conversation stopped so I'm wondering if you got any progress on the update? I have created a Discord server for WD modding and quite a few people joined to mod WD; this injector would really help in some cases :)
